"""Initial schema

Revision ID: 357c8550d7d0
Revises: 
Create Date: 2026-09-26 17:40:47.564196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '357c8550d7d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('software_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=100), nullable=False),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('minor', sa.Integer(), nullable=True),
    sa.Column('patch', sa.Integer(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('OFFICIAL_DOCS', 'GITHUB_REPO', 'GITHUB_ISSUES', 'STACK_OVERFLOW', 'YOUTUBE', 'COMMUNITY_DOCS', 'BLOG', 'RFC', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('authority_level', sa.Enum('OFFICIAL', 'COMMUNITY', 'AUTO_GENERATED', name='authoritylevel'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('crawl_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('GUIDE', 'REFERENCE', 'TUTORIAL', 'CHANGELOG', 'API_DOCS', 'ISSUE', 'DISCUSSION', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_software_versions',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('software_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['software_version_id'], ['software_versions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'software_version_id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('heading_level', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('OFFICIAL_DOCS', 'GITHUB_REPO', 'GITHUB_ISSUES', 'STACK_OVERFLOW', 'YOUTUBE', 'COMMUNITY_DOCS', 'BLOG', 'RFC', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('authority_level', sa.Enum('OFFICIAL', 'COMMUNITY', 'AUTO_GENERATED', name='authoritylevel'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.Enum('TEXT', 'CODE', 'TABLE', 'HEADING', 'MIXED', name='chunktype'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('position_in_section', sa.Integer(), nullable=False),
    sa.Column('position_in_document', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_software_versions',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('software_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['software_version_id'], ['software_versions.id'], ),
    sa.PrimaryKeyConstraint('chunk_id', 'software_version_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_software_versions')
    op.drop_table('chunks')
    op.drop_table('sections')
    op.drop_table('document_versions')
    op.drop_table('source_software_versions')
    op.drop_table('documents')
    op.drop_table('sources')
    op.drop_table('software_versions')
    op.drop_table('software')
    # ### end Alembic commands ###
